---
title: "Piracy Notebook v2"
author: "Gavin McDonald"
output: 
  html_notebook: 
    number_sections: yes
    toc: yes
date: "March 30, 2017"
---
# Introduction

# Methods
## Load necessary libraries
```{r load_libraries}
library(rgdal)
library(sp)
library(leaflet)
library(lubridate)
library(tidyverse)
library(raster)
library(bigrquery)
library(RcppRoll)
library(broom)
```
## Load anti-shipping activity messages
Data from http://msi.nga.mil/NGAPortal/MSI.portal?_nfpb=true&_pageLabel=msi_portal_page_65
```{r load_data, results='hide',error=FALSE,message=FALSE,warning=FALSE}
## load anti-shipping data
ASAM <- readOGR(dsn = "data/ASAM_shp", layer = "ASAM 18 JAN 17", stringsAsFactors = FALSE)
## Process dates, and filter out anything before 2012
ASAM@data <- ASAM@data %>%
  mutate(Date = as_date(DateOfOcc),
         Year = year(Date)) %>%
  dplyr::select(-DateOfOcc)

vesselTypes <- unique(ASAM@data$Victim)[grepl("Fish",unique(ASAM@data$Victim)) | grepl("FISH",unique(ASAM@data$Victim)) | grepl("fish",unique(ASAM@data$Victim))]

ASAM <- ASAM %>%
  subset(Year > 2012 & Year < 2017)
  # subset(Victim %in% vesselTypes)
## Remove duplicates
ASAM <- remove.duplicates(ASAM)
## read in EEZ
eez <- readOGR(dsn = "data/World_EEZ_v9_20161021_LR", layer = "eez_lr", stringsAsFactors = FALSE)

## set projection
proj4string(ASAM)<-proj4string(eez)

## look only at events happening within eezs
eezASAMOverlap <- overlay<-raster::intersect(ASAM,eez)
## events in high seas
highSeasOverlap <- subset(ASAM,!(Reference %in% eezASAMOverlap@data$Reference))

highSeasOverlap@data <- highSeasOverlap@data %>%
  mutate(PolygonID = NA,
         MRGID = NA,
         GeoName = "High Seas",
         Pol_type = NA,
         MRGID_Ter1 = NA,
         Territory1 = NA,
         MRGID_Sov1 = NA,
         Sovereign1 = NA,
         ISO_Ter1 = NA,
         MRGID_Ter2 = NA,
         Territory2 = NA,
         MRGID_Sov2 = NA,
         Sovereign2 = NA,
         ISO_Ter2 = NA,
         MRGID_Ter3 = NA,
         Territory3 = NA,
         MRGID_Sov3 = NA,
         Sovereign3 = NA,
         ISO_Ter3 = NA,
         x_1 = NA,
         y_1 = NA,
         Area_km2 = NA,
         MRGID_EEZ = NA)
  
masterAttacks <- eezASAMOverlap %>%
  rbind(highSeasOverlap) %>%
  remove.duplicates()
detach("package:rgdal", unload=TRUE)
```

## Plot attack data
```{r attackPlot}

data.frame(country=gsub(" Exclusive Economic Zone"," EEZ",masterAttacks@data$GeoName)) %>%
  group_by(country) %>%
  summarize(n = n()) %>%
  filter(n > 10) %>%
  ggplot(aes(x=reorder(country,-n),y=n)) +
           geom_histogram(stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("Country") +
  ylab("Number of attacks\n2012 - 2016")

countryList <- masterAttacks@data %>%
  as_data_frame() %>%
  group_by(ISO_Ter1) %>%
  summarize(n = n()) %>%
  filter(n > 10) %>%
  arrange(-n) %>%
  dplyr::select(eez_iso3 = ISO_Ter1) %>%
  mutate(eez_iso3=replace(eez_iso3, is.na(eez_iso3), "null")) %>%
  as.vector()

```

## Plot locations of attacks

```{r plot}
leaflet() %>%
  # fitBounds(0, 60, 35, 72) %>%
  addPolygons(data = eez,
    fillOpacity = 0.15, 
    fillColor = "blue", 
    stroke=TRUE,
    weight=1,
    color="black",
    popup = ~paste0("<font color=#000000>",
      "<b>EEZ: </b>", GeoName, "<br>",
    "</font>"))  %>%
  addCircleMarkers(data=masterAttacks,
              color="red",
              stroke=FALSE,
              fillOpacity = 0.5,
              radius = 3,
              popup = ~paste0("<font color=#000000>",
                "<b>Reference ID: </b>", Reference, "<br>",
                "<b>EEZ: </b>", GeoName, "<br>",
                "<b>Date: </b>", Date, "<br>",
                "<b>Aggressor: </b>", Aggressor, "<br>",
                "<b>Victim: </b>", Victim, "<br>",
                "<b>Description: </b>", gsub("NA","",paste(Desc1,Desc2,Desc3,Desc4,Desc5,Desc6,sep=" ")), "<br>",
                 "</font>"))
  
```

## Load GFW data

```{r GFWdata}
# grid_resolution_degree <- 0.25 # Set resolution of raster grid, degrees
# fishingEffort <- lapply(countryList$eez_iso3, function(x){
#   print(x)
#   sql <-  paste("SELECT
#     eez_iso3,
#     FLOOR(lat/",grid_resolution_degree,") * ",grid_resolution_degree," lat_bin,
#     FLOOR(lon/",grid_resolution_degree,") * ",grid_resolution_degree," lon_bin,
#     DATE(timestamp) Date,
#     SUM(hours) total_hours,
#     COUNT(DISTINCT mmsi) total_vessels
#   FROM
#     all_fishing_effort.all_fishing_effort_all_years
#   WHERE
#     eez_iso3 = '",x,"'
#   AND
#     measure_new_score >=.5
#   AND
#     NOT (distance_from_shore < 1000 AND implied_speed < 1)
#   GROUP BY
#     eez_iso3,
#     lat_bin,
#     lon_bin,
#     Date",
#     sep="")
#   project <-  "ucsb-gfw"
#   binned_effort <- query_exec(sql,project,max_pages = Inf)
# }) %>%
#   bind_rows()
# save(fishingEffort,file="data/eezFishingEffort.Rdata")
load("data/eezFishingEffort.Rdata")
```

```{r}
latLonCombos <- fishingEffort %>%
  as_tibble() %>%
  dplyr::select(lon_bin,
                lat_bin) %>%
  distinct()

distanceThreshold <- 50

latLonAttackDF <- map(masterAttacks@data$Reference, function(x){
  temp <- subset(masterAttacks,masterAttacks@data$Reference == x)
  results <- spDistsN1(latLonCombos %>%
                         as.matrix,
                       temp,
                       longlat=TRUE)
  df <- latLonCombos %>%
    mutate(Distance = results,
           Reference = x,
           Date = date(temp@data$Date))
}) %>%
  bind_rows() %>%
  filter(Distance <= distanceThreshold) %>%
  group_by(lon_bin,lat_bin,Date) %>%
  summarize(number_attacks = n())

recentDaysThreshold <- 7

enso <- 
  read_table("http://www.esrl.noaa.gov/psd/gcos_wgsp/Timeseries/Data/nino34.long.anom.data",
             na = c("-99.99", "99.99"), skip = 1, n_max = year(Sys.time()) - 1870 + 1,
             col_names = c("Year", 1:12)) %>%
  filter(Year >= 2011) %>%
  filter(Year <= 2016) %>%
  gather(Month, enso, -Year) %>%
  mutate(Month = as.double(Month),
         enso = ifelse(is.na(enso),mean(enso,na.rm=TRUE),enso))

processedFishingEffort <- fishingEffort %>%
  mutate(Date = date(Date)) %>%
  left_join(latLonAttackDF,by = c("lat_bin", "lon_bin", "Date")) %>%
  mutate(number_attacks=replace(number_attacks, is.na(number_attacks), 0)) %>%
  complete(nesting(lat_bin, lon_bin,eez_iso3),
       Date=seq(from=min(.$Date)-recentDaysThreshold,to=max(.$Date), by=1), 
       fill=list(total_hours=0,
                 total_vessels=0,
                 number_attacks=0)) %>%
  mutate(number_attacks_recent=roll_sum(x=number_attacks!=0, n=recentDaysThreshold, fill=0, align="right"),
         Month = month(Date),
         Year = year(Date)) %>%
  left_join(enso,by=c("Month","Year"))
         
# piracyModel <- glm(total_hours ~ number_attacks_recent + factor(eez_iso3) + factor(wday(Date)) + factor(Month),
#                    family="poisson",
#                    data=processedFishingEffort)
# 
# summary(piracyModel)
```
