---
title: "Piracy Notebook"
author: "Gavin McDonald"
output: 
  html_notebook: 
    number_sections: yes
    toc: yes
date: "January 18, 2017"
---
# Introduction

# Methods
## Load necessary libraries
```{r load_libraries}
library(rgdal)
library(sp)
library(rgeos)
library(mapproj)
library(leaflet)
library(googlesheets)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(readr)
library(broom)
library(geosphere)
library(raster)
library(bigrquery)
```
## Load anti-shipping activity messages
```{r load_data, results='hide',error=FALSE,message=FALSE,warning=FALSE}
## load anti-shipping data
ASAM <- readOGR(dsn = "data/ASAM_shp", layer = "ASAM 18 JAN 17", stringsAsFactors = FALSE)
## Process dates, and filter out anything before 2012
ASAM@data <- ASAM@data %>%
  mutate(Date = as_date(DateOfOcc),
         Year = year(Date)) %>%
  dplyr::select(-DateOfOcc)

ASAM <- ASAM %>%
  subset(Year > 2012)
## Remove duplicates
ASAM <- remove.duplicates(ASAM)
## read in EEZ
eez <- readOGR(dsn = "data/World_EEZ_v9_20161021_LR", layer = "eez_lr", stringsAsFactors = FALSE)

## set projection
proj4string(ASAM)<-proj4string(eez)

## look only at events happening within eezs
eezASAMOverlap <- overlay<-raster::intersect(ASAM,eez)
## set world base map
world <- map("world", fill = TRUE, plot = FALSE)
```
## Set up buffers and controls
```{r buffer}
## Just look at Somalia
somaliPiracy <- eezASAMOverlap %>%
  #subset(Aggressor == "Pirates") %>%
  subset(GeoName == "Somali Exclusive Economic Zone")

eezSomalia <- eez %>%
  subset(GeoName == "Somali Exclusive Economic Zone")

impactZones <- gBuffer(somaliPiracy,width=0.25,byid=TRUE) %>%
  SpatialPolygonsDataFrame(data=somaliPiracy@data,match.ID=TRUE)
impactZones@data$Control <- "Impact"

controlZones <- impactZones %>%
  gBuffer(width=0.25,byid=TRUE) 

controlZones<- controlZones - impactZones
controlZones@data$Control <- "Control"

## Only look inside Somalia EEZ
impactZones <- raster::intersect(impactZones,eezSomalia)
controlZones <- raster::intersect(controlZones,eezSomalia)
```


## Plot locations of attacks

```{r plot}

leaflet(data = world) %>%
  # fitBounds(0, 60, 35, 72) %>%
  addPolygons(
    stroke = FALSE, fillOpacity = 1, smoothFactor = 1, color = "white"
  )  %>%
  addPolygons(
    data = eezSomalia,
    group = "eez",
    stroke=TRUE,
    weight=1,
    popup = ~paste0(
      "<b>EEZ: </b>", GeoName, "<br>")) %>%
  addMarkers(
    data = somaliPiracy,
    popup = ~paste0(
      "<b>Reference ID: </b>", Reference, "<br>",
       "<b>EEZ: </b>", GeoName, "<br>",
      "<b>Date: </b>", Date, "<br>",
      "<b>Aggressor: </b>", Aggressor, "<br>",
      "<b>Victim: </b>", Victim, "<br>",
      "<b>Description: </b>", gsub("NA","",paste0(Desc1,Desc2,Desc3,Desc4,Desc5,Desc6,sep=" ")), "<br>")) %>%
  addPolygons(data=impactZones,
              color="red",
              stroke=FALSE,
              fillOpacity = 0.5,
    popup = ~paste0(
      "<b>Reference ID: </b>", Reference, "<br>",
       "<b>EEZ: </b>", GeoName.1, "<br>",
      "<b>Zone type: </b>", Control, "<br>",
      "<b>Date: </b>", Date, "<br>",
      "<b>Aggressor: </b>", Aggressor, "<br>",
      "<b>Victim: </b>", Victim, "<br>",
      "<b>Description: </b>", gsub("NA","",paste0(Desc1,Desc2,Desc3,Desc4,Desc5,Desc6,sep=" ")), "<br>")) %>%
  addPolygons(data=controlZones,
              color="green",
              stroke=FALSE,
              fillOpacity = 0.5,
    popup = ~paste0(
      "<b>Reference ID: </b>", Reference, "<br>",
       "<b>EEZ: </b>", GeoName.2, "<br>",
      "<b>Zone type: </b>", Control, "<br>",
      "<b>Date: </b>", Date, "<br>",
      "<b>Aggressor: </b>", Aggressor, "<br>",
      "<b>Victim: </b>", Victim, "<br>",
      "<b>Description: </b>", gsub("NA","",paste0(Desc1,Desc2,Desc3,Desc4,Desc5,Desc6,sep=" ")), "<br>")) %>%
  fitBounds(xmin(extent(eezSomalia)), ymin(extent(eezSomalia)), xmax(extent(eezSomalia)), ymax(extent(eezSomalia)))
```

## Load GFW data

```{r GFWdata}
## Create bounding box around each zone
boxes <- lapply(controlZones@data$Reference,function(x){
  temp <- subset(controlZones,Reference == x)
  box <- bbox(temp) %>%
    as_data_frame
  
  box <- cbind(box[1,],box[2,])
  colnames(box) <- c("min_lon", "min_lat","max_lon","max_lat")
  box <- box %>%
    as_data_frame %>%
    mutate(Reference = x)
}) %>%
  bind_rows()

GFW_connection <- src_bigquery("ucsb-gfw", "fao_v2", max_pages = Inf)
fao_file <- "all_years_clean_effort"

fishingEffort <- lapply(c("2016-209"), function(x){
#fishingEffort <- lapply(somaliPiracy@data$Reference, function(x){
  tempBox <- boxes[which(boxes$Reference == x),]
  max_lat <- tempBox$max_lat
  min_lat <- tempBox$min_lat
  max_lon <- tempBox$max_lon
  min_lon <- tempBox$min_lon
  
  tbl(GFW_connection, from = fao_file) %>%
    select(timestamp, lon, lat, hours, measure_new_score) %>%
    filter(
      lat < max_lat &
        lat > min_lat &
        lon < max_lon &
        lon > min_lon &
        measure_new_score > 0.5
    ) %>%
    collect(n=Inf) %>%
    mutate(Reference = tempBox$Reference)
})   %>%
  ## bind over all attacks
  bind_rows()
```

