---
title: "Piracy Notebook v2"
author: "Gavin McDonald"
date: "March 30, 2017"
output:
  html_document:
    df_print: paged
    toc: yes
  html_notebook:
    number_sections: yes
    toc: yes
---
# Introduction

# Methods
## Load necessary libraries
```{r load_libraries}
library(leaflet)
library(sf)
library(lubridate)
library(tidyverse)
library(bigrquery)
library(viridis)
library(maps)
library(zoo)
```
## Load anti-shipping activity messages
Data from http://msi.nga.mil/NGAPortal/MSI.portal?_nfpb=true&_pageLabel=msi_portal_page_65
```{r load_data, results='hide',error=FALSE,message=FALSE,warning=FALSE}
# Read in EEZ data
# Marine Regions V9
eez <- read_sf(dsn = "../raw_data/World_EEZ_v9_20161021_LR", layer = "eez_lr", stringsAsFactors = FALSE)

## load anti-shipping data
## Process dates, and filter out anything before 2010
# Join to eez data to figure out which eez each attack happens in
ASAM <- read_sf(dsn = "../raw_data/ASAM_shp", layer = "ASAM 20 MAR 18", stringsAsFactors = FALSE) %>%
  mutate(Date = as_date(DateOfOcc),
         Year = year(Date)) %>%
  dplyr::select(-DateOfOcc) %>%
  filter(Year > 2010 & Year < 2018) %>%
  `st_crs<-`(st_crs(eez)) %>%
  st_join(eez, join = st_intersects) %>%
  mutate(attack_eez = ifelse(is.na(ISO_Ter1),"High Seas",as.character(ISO_Ter1)))

# Define cell size for hot spot map
cell_size <- 5 #degrees
one_over_cellsize = 1/cell_size

ASAM <- do.call(rbind, st_geometry(ASAM)) %>% 
  as_tibble() %>% 
  cbind(ASAM$Year,
        ASAM$Date,
        ASAM$Aggressor,
        ASAM$Victim,
        ASAM$attack_eez) %>%
  setNames(c("lon","lat","year","date","aggressor","victim","attack_eez")) %>%
  mutate(lon_bin = floor(lon*one_over_cellsize)/one_over_cellsize,
         lat_bin = floor(lat*one_over_cellsize)/one_over_cellsize) 

# Group by bins, summarize, and add hotspot id
ASAM_binned <- ASAM %>%
  group_by(year,lon_bin,lat_bin) %>%
  summarize(number_attacks = n()) %>%
  ungroup()

hotspots <- distinct(ASAM_binned %>% dplyr::select(lon_bin,lat_bin)) %>%
  mutate(hotspot_id = 1:n())


ASAM_binned <- ASAM_binned %>%
  left_join(hotspots, by = c("lat_bin","lon_bin"))

ASAM <- ASAM %>%
  left_join(ASAM_binned %>%
              dplyr::select(year,lon_bin,lat_bin,hotspot_id),by = c("year", "lon_bin", "lat_bin")) %>%
  dplyr::select(date,year,lat,lon,lat_bin,lon_bin,hotspot_id,aggressor,victim,attack_eez)


write_csv(ASAM,"../processed_data/attacks.csv")

date_range <- seq(ymd('2011-01-01'),ymd('2017-12-31'), by = '1 day')

expanded_asam <- expand.grid(date = date_range,
                             hotspot_id = hotspots$hotspot_id) %>%
  left_join(hotspots,by="hotspot_id") %>%
  left_join(ASAM %>%
              dplyr::select(date,
                            lon_bin,
                            lat_bin,
                            attack_eez) %>%
              group_by(date,lon_bin,lat_bin) %>%
              summarize(number_attacks = n()),by=c("date","lon_bin","lat_bin")) %>%
  mutate(attacks_30_days = rollapplyr(number_attacks, width = 30, FUN = sum, na.rm=TRUE, partial = TRUE))

# ideas for days elapsed: https://stackoverflow.com/questions/26553638/calculate-elapsed-time-since-last-event/26554441
```

## Global attack visualization
```{r attack_histogram}
ASAM %>%
  group_by(attack_eez) %>%
  summarize(n = n()) %>%
  filter(n > 10) %>%
  ggplot(aes(x=reorder(attack_eez,-n),y=n)) +
           geom_histogram(stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("Country") +
  ylab("Number of attacks\n2010 - 2018")
```

## Plot locations of attacks

```{r interactive_map}
library(raster)
attack_raster <- ASAM_binned %>% 
  group_by(hotspot_id) %>% 
  summarize(lon_bin = lon_bin[1], 
            lat_bin = lat_bin[1],
            number_attacks = sum(number_attacks)) %>%
  dplyr::select(lon_bin, lat_bin,number_attacks)

attack_raster <-  rasterFromXYZ(attack_raster, crs = st_crs(eez)$proj4string)

leaflet() %>%
  # fitBounds(0, 60, 35, 72) %>%
  addPolygons(data = eez,
    fillOpacity = 0.15, 
    fillColor = "blue", 
    stroke=TRUE,
    weight=1,
    color="black",
    popup = ~paste0("<font color=#000000>",
      "<b>EEZ: </b>", GeoName, "<br>",
    "</font>"))  %>%
  addRasterImage(attack_raster, opacity = 0.5) %>%
  addCircleMarkers(data=ASAM %>%
                     st_as_sf(coords = c("lon","lat")) %>%
                     `st_crs<-`(st_crs(eez)),
              color="red",
              stroke=FALSE,
              fillOpacity = 0.5,
              radius = 3,
              popup = ~paste0("<font color=#000000>",
                "<b>EEZ: </b>", attack_eez, "<br>",
                "<b>Hotspot ID: </b>", hotspot_id, "<br>",
                "<b>Date: </b>", date, "<br>",
                "<b>Aggressor: </b>", aggressor, "<br>",
                "<b>Victim: </b>", victim, "<br>",
                 "</font>"))
  
```

```{r attack_raster}
wrld = st_as_sf(maps::map('world', plot=F, fill=T))
# Make attack plot for every year
  ggplot() +  
    geom_raster(data = ASAM_binned,
                aes(x = lon_bin, y = lat_bin, fill=number_attacks)) + 
    scale_fill_viridis(na.value="white",name="Number of\nAttacks") +
    facet_wrap(~year, ncol = 2) +
    geom_sf(data = wrld,
            fill = "darkgrey",
            lwd = 0) +
    theme_bw() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major = element_line(colour = "white"),
        panel.grid.minor = element_line(color = "white"))

```

