---
title: "Piracy Notebook v2"
author: "Gavin McDonald"
date: "April 10, 2017"
output:
  html_document:
    df_print: paged
    toc: yes
  html_notebook:
    number_sections: yes
    toc: yes
---
# Introduction

# Methods
## Load necessary libraries
```{r load_libraries}
library(leaflet)
library(sf)
library(lubridate)
library(tidyverse)
library(viridis)
```


## Global attack visualization
```{r attack_histogram}
ASAM <- read_csv("../processed_data/attacks.csv")
ASAM %>%
  group_by(attack_eez) %>%
  summarize(n = n()) %>%
  filter(n > 10) %>%
  ggplot(aes(x=reorder(attack_eez,-n),y=n)) +
           geom_histogram(stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("Country") +
  ylab("Number of attacks\n2010 - 2018")
```

## Plot locations of attacks

```{r interactive_map}
# leaflet() %>%
#   # fitBounds(0, 60, 35, 72) %>%
#   addPolygons(data = eez,
#     fillOpacity = 0.15, 
#     fillColor = "blue", 
#     stroke=TRUE,
#     weight=1,
#     color="black",
#     popup = ~paste0("<font color=#000000>",
#       "<b>EEZ: </b>", GeoName, "<br>",
#     "</font>"))  %>%
#   addCircleMarkers(data=ASAM %>%
#                      st_as_sf(coords = c("lon","lat")) %>%
#                      `st_crs<-`(st_crs(eez)),
#               color="red",
#               stroke=FALSE,
#               fillOpacity = 0.5,
#               radius = 3,
#               popup = ~paste0("<font color=#000000>",
#                 "<b>EEZ: </b>", attack_eez, "<br>",
#                 "<b>Hotspot ID: </b>", hotspot_id, "<br>",
#                 "<b>Date: </b>", date, "<br>",
#                 "<b>Aggressor: </b>", aggressor, "<br>",
#                 "<b>Victim: </b>", victim, "<br>",
#                  "</font>"))
  
```

```{r attack_plots}
# Projection
proj <- "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84"

# Download and read in world land data
# download.file(url="http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_land.zip", "ne_110m_land.zip", "auto")
# unzip("ne_110m_land.zip")
# file.remove("ne_110m_land.zip")

world.land <- read_sf(dsn = "../raw_data/ne_110m_land", layer = "ne_110m_land", stringsAsFactors = FALSE)
# ASAM_binned <- read.csv("../processed_data/ASAM_binned.csv", stringsAsFactors = F)
# 
# attack_lat_limits <- c(min(ASAM_binned$lat_bin) - 5, max(ASAM_binned$lat_bin) + 5)
# attack_lon_limits <- c(min(ASAM_binned$lon_bin) - 5, max(ASAM_binned$lon_bin) + 5)
# # # Make attack plot for every year
# p_all_years <-  ggplot() +
#     geom_tile(data = ASAM_binned %>%
#               group_by(lon_bin,lat_bin,year) %>%
#               summarize(number_attacks = sum(number_attacks)),
#                 aes(x = lon_bin, y = lat_bin, alpha=number_attacks),fill = "red",size=0.25) + 
#     scale_alpha(name = "Number of Encounters",range=c(0.3,0.85), na.value = 0) +
#             geom_sf(data = world.land,
#             fill = "darkgrey",
#             lwd = 0) +
#     theme_bw() +
#   theme(axis.title.x=element_blank(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank(),
#         axis.title.y=element_blank(),
#         axis.text.y=element_blank(),
#         axis.ticks.y=element_blank(),
#         panel.grid.major = element_line(colour = "black"),
#         panel.grid.minor = element_line(color = "black"),
#         strip.background =element_rect(fill="white"),
#         panel.background = element_rect(fill = 'black')) +
#     facet_wrap(~year, ncol = 2) +
#       guides(fill = guide_colourbar(barheight = 3.25, barwidth = 3.25)) +
#   theme(legend.position = c(1, 0),
#         legend.justification = c(1, 0),
#         legend.direction="horizontal") +
#       ylim(attack_lat_limits) +
#     xlim(attack_lon_limits)
# 
# p_all_years_bw <-  ggplot() +
#     geom_tile(data = ASAM_binned %>%
#               group_by(lon_bin,lat_bin,year) %>%
#               summarize(number_attacks = sum(number_attacks)),
#                 aes(x = lon_bin, y = lat_bin, alpha=number_attacks),fill = "darkgray",color="darkgray",size=0.25) + 
#     scale_alpha(name = "Number of Encounters",range=c(0.1,0.9), na.value = 0) +
#             geom_sf(data = world.land,
#             fill = "darkgrey",
#             lwd = 0) +
#     theme_bw() +
#   theme(axis.title.x=element_blank(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank(),
#         axis.title.y=element_blank(),
#         axis.text.y=element_blank(),
#         axis.ticks.y=element_blank(),
#         panel.grid.major = element_line(colour = "black"),
#         panel.grid.minor = element_line(color = "black"),
#         strip.background =element_rect(fill="white"),
#         panel.background = element_rect(fill = 'black')) +
#     facet_wrap(~year, ncol = 2) +
#       guides(fill = guide_colourbar(barheight = 3.25, barwidth = 3.25)) +
#   theme(legend.position = c(1, 0),
#         legend.justification = c(1, 0),
#         legend.direction="horizontal") +
#       ylim(attack_lat_limits) +
#     xlim(attack_lon_limits)
# 
# ggsave(filename = "../figs/attacks_by_year.eps", plot = p_all_years, device = cairo_ps, width = 8.5, height = 6)
# ggsave(filename = "../figs/attacks_by_year_bw.eps", plot = p_all_years_bw, device = cairo_ps, width = 8.5, height = 6)
```

```{r cluster_map}
library(scico)
palette = setNames(c(scico(3, palette = 'roma'),"darkgrey"),c("Gulf of Guinea","Gulf of Aden","Southeast Asia","Outside of Hotspots"))

palette_bw = setNames(c(gray.colors(3),"black"),c("Gulf of Guinea","Gulf of Aden","Southeast Asia","Outside of Hotspots"))

ASAM$Hotspot <- factor(ASAM$Hotspot, levels = c("Gulf of Guinea","Gulf of Aden","Southeast Asia","Outside of Hotspots"))


attack_time_series <- ASAM %>%
  group_by(year,Hotspot) %>%
  summarize(number_attacks = n()) %>%
  ungroup() %>%
  mutate(Hotspot = fct_relevel(Hotspot,c("Gulf of Guinea","Gulf of Aden","Southeast Asia","Outside of Hotspots"))) %>%
  ggplot(aes(x=year,y=number_attacks)) +
  geom_bar(stat="identity",aes(fill=Hotspot)) +
  scale_x_continuous(breaks=unique(ASAM$year)) +
  scale_fill_manual(values = palette) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("Year") +
  ylab("Number of Encounters")

attack_time_series_bw <- ASAM %>%
  group_by(year,Hotspot) %>%
  summarize(number_attacks = n()) %>%
  ungroup() %>%
    mutate(Hotspot = fct_relevel(Hotspot,c("Gulf of Guinea","Gulf of Aden","Southeast Asia","Outside of Hotspots"))) %>%
  ggplot(aes(x=year,y=number_attacks)) +
  geom_bar(stat="identity",aes(fill=Hotspot),color="black",size=0.25) +
  scale_fill_manual(values = palette_bw) +
  scale_x_continuous(breaks=unique(ASAM$year)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("Year") +
  ylab("Number of Encounters")
cluster_boxes <- read_csv("../processed_data/cluster_boxes.csv") %>%
  mutate(cluster_num=c(1,3,4,2))
cluster_boxes_map <- cluster_boxes %>%
  rowwise() %>%
  mutate(geometry = st_geometry(st_polygon(list(rbind(c(lon_min,lat_min), c(lon_max,lat_min), c(lon_max,lat_max), c(lon_min,lat_max), c(lon_min,lat_min)))))) %>%
  st_as_sf(sf_column_name = "geometry") %>%
  `st_crs<-`(st_crs(world.land))

cluster_lat_limits <- c(min(cluster_boxes_map$lat_min) - 10, max(cluster_boxes_map$lat_max) + 10)
cluster_lon_limits <- c(min(cluster_boxes_map$lon_min) - 2, max(cluster_boxes_map$lon_max) + 2)

cluster_plot <-   ggplot() +
  theme_bw() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major = element_line(colour = "black"),
        panel.grid.minor = element_line(color = "black"),
        strip.background =element_rect(fill="white"),
        panel.background = element_rect(fill = 'black'),
        plot.margin=grid::unit(c(0,0,0,0), "mm")) +
  #geom_point(data = ASAM %>% filter(!str_detect(cluster,"_0") & year > 2011), aes(x=lon,y=lat,color=cluster)) +
        ylim(cluster_lat_limits) +
        xlim(cluster_lon_limits)
  #viridis::scale_fill_viridis(discrete = TRUE,option="B",begin=0.25)

cluster_plot_color <- cluster_plot +
    geom_sf(data = cluster_boxes_map,aes(fill=Hotspot),color="black") +
    scale_fill_manual(values = palette) +
    geom_sf(data = world.land,
          fill = "darkgrey",
          lwd = 0)

cluster_plot_bw <- cluster_plot +
    geom_sf(data = cluster_boxes_map,aes(fill=Hotspot),color="white") +
    scale_fill_manual(values = palette_bw) +
    geom_sf(data = world.land,
          color="white",
          fill = "darkgrey",
          lwd = 0)

#ggsave(filename = "../figs/cluster_plot.eps", plot = cluster_plot_color, device = cairo_ps, width = 8.5, height = 4)

#ggsave(filename = "../figs/attack_time_series.eps", plot = attack_time_series, device = cairo_ps, width = 8.5, height = 6)

#ggsave(filename = "../figs/cluster_plot_bw.eps", plot = cluster_plot_bw, device = cairo_ps, width = 8.5, height = 4)

ggsave(filename = "../figs/attack_time_series_bw.eps", plot = attack_time_series_bw, device = cairo_ps, width = 8.5, height = 6)
```

```{r shipping_plot}
# gridded_shipping_hours_processed <- read_csv("../processed_data/gridded_shipping_hours_processed.csv")
# 
# fancy_scientific <- function(l) {
#      # turn in to character string in scientific notation
#      l <- format(signif(l,3), scientific = TRUE)
#      # quote the part before the exponent to keep all the digits
#      l <- gsub("^(.*)e", "'\\1'e", l)
#      # turn the 'e+' into plotmath format
#      l <- gsub("e", "%*%10^", l)
#      # return this as an expression
#      parse(text=l)
# }
# 
# 
# shipping_piracy_overlay <-   ggplot() +
#   geom_tile(data = gridded_shipping_hours_processed %>%
#               filter(hours > 100),
#             aes(x = lon_bin, y = lat_bin, fill=hours), 
#             colour = NA, na.rm = TRUE)+
#     #scale_fill_viridis(na.value="white",name="Number of Attacks",option = "C", direction = -1, end = 0.95) +
#   theme_bw() +
#   theme(axis.title.x=element_blank(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank(),
#         axis.title.y=element_blank(),
#         axis.text.y=element_blank(),
#         axis.ticks.y=element_blank(),
#         panel.grid.major = element_line(colour = "black"),
#         panel.grid.minor = element_line(color = "black"),
#         strip.background =element_rect(fill="white"),
#         panel.background = element_rect(fill = 'black'),
#         plot.margin=grid::unit(c(0,0,0,0), "mm"))
# 
# overlay_fig_color <- shipping_piracy_overlay + 
#   scale_fill_gradient2(name="Shipping Hours", low = "white", mid = "dodgerblue",high = "white",na.value = "black", trans = "log", midpoint = log(25000),labels=fancy_scientific) +
#   geom_tile(data = ASAM_binned %>%
#               filter(year > 2011) %>%
#               group_by(lon_bin,lat_bin) %>%
#               summarize(number_attacks = sum(number_attacks)),
#                 aes(x = lon_bin, y = lat_bin, alpha=number_attacks), fill = "red")+ 
#     scale_alpha(name = "Number of Encounters",range=c(0.3,0.85), na.value = 0) +
#       geom_sf(data = world.land,
#           fill = "darkgrey",
#           lwd = 0)+
#     geom_sf(data = cluster_boxes_map,color="white",fill=NA,size=1) +
# geom_text(data = cluster_boxes,aes(label = cluster_num, x=lon_max + 5, y=lat_max + 5),color="white")
# 
# overlay_fig_bw <- shipping_piracy_overlay + 
#   scale_fill_gradient2(name="Shipping Hours", low = "black", mid = "gray",high = "white",na.value = "black", trans = "log", midpoint = log(30000),labels=fancy_scientific) +
#   geom_tile(data = ASAM_binned %>%
#               filter(year > 2011) %>%
#               group_by(lon_bin,lat_bin) %>%
#               summarize(number_attacks = sum(number_attacks)),
#                 aes(x = lon_bin, y = lat_bin, alpha=number_attacks), fill = "darkgray",color="darkgray",size=0.25) + 
#     scale_alpha(name = "Number of Encounters",range=c(0.1,1), na.value = 0) +
#       geom_sf(data = world.land,
#           fill = "darkgrey",
#           lwd = 0)+
#     geom_sf(data = cluster_boxes_map,color="white",fill=NA,size=1) +
# geom_text(data = cluster_boxes,aes(label = cluster_num, x=lon_max + 5, y=lat_max + 5),color="white")
# 
# ggsave(filename = "../figs/shipping_piracy_overlay.eps", plot = overlay_fig_color, device = cairo_ps, width = 8.5, height = 8.5/2)
# 
# 
# ggsave(filename = "../figs/shipping_piracy_overlay_bw.eps", plot = overlay_fig_bw, device = cairo_ps, width = 8.5, height = 8.5/2)
```

```{r shipping_plot2}
gridded_shipping_hours_processed <- read_csv("../processed_data/gridded_shipping_hours_processed.csv")

fancy_scientific <- function(l) {
     # turn in to character string in scientific notation
     l <- format(signif(l,3), scientific = TRUE)
     # quote the part before the exponent to keep all the digits
     l <- gsub("^(.*)e", "'\\1'e", l)
     # turn the 'e+' into plotmath format
     l <- gsub("e", "%*%10^", l)
     # return this as an expression
     parse(text=l)
}


overlay_fig_bw <-   ggplot() +
  geom_tile(data = gridded_shipping_hours_processed %>%
              filter(hours > 100),
            aes(x = lon_bin, y = lat_bin, fill=hours), 
            colour = NA, na.rm = TRUE)+
    #scale_fill_viridis(na.value="white",name="Number of Attacks",option = "C", direction = -1, end = 0.95) +
  theme_bw() +
  theme(plot.title = element_text(size=15),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title=element_text(size=15),
        legend.text=element_text(size=15),
        panel.grid.major = element_line(colour = "white"),
        panel.grid.minor = element_line(color = "white"),
        strip.background =element_rect(fill="white"),
        panel.background = element_rect(fill = 'white'),
        plot.margin=grid::unit(c(0,0,0,0), "mm"))+ 
  scale_fill_gradient2(name="Shipping Hours", low = "white", mid = "gray35",high = "black",na.value = "white", trans = "log", midpoint = log(30000),labels=fancy_scientific,breaks = c(1e3,1e4,1e5)) +
      geom_sf(data = world.land,
          fill = "darkgrey",
          lwd = 0)+ 
  ylim(c(-55,90)) +
  geom_point(data = ASAM, aes(x = lon, y = lat),size = 0.1) +
    geom_sf(data = cluster_boxes_map,color="black",fill=NA,size=1) +
geom_text(data = cluster_boxes %>% 
  mutate(lat_label = ifelse(cluster == "hotspot_malacca_straits",lat_max + 8,lat_max +6),
         lon_label = ifelse(cluster == "hotspot_malacca_straits",lon_max - (lon_max - lon_min)/2,lon_max +6)),aes(label = cluster_num, x=lon_label, y=lat_label),color="black",size = 8) + guides(fill=guide_legend(
                 keywidth=0.25,
                 keyheight=0.25,
                 default.unit="inch")
      )

ggsave(filename = "../figs/shipping_piracy_overlay_bw.eps", plot = overlay_fig_bw, width = 8.5, height = 8.5/2)

ggsave(filename = "../figs/shipping_piracy_overlay_bw_preso.eps", plot = ggplot() +
  geom_tile(data = gridded_shipping_hours_processed %>%
              filter(hours > 100),
            aes(x = lon_bin, y = lat_bin, fill=hours), 
            colour = NA, na.rm = TRUE)+
  #scale_fill_viridis(na.value="white",name="Number of Attacks",option = "C", direction = -1, end = 0.95) +
  theme_bw() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title=element_text(size=20),
        legend.text=element_text(size=20),
        strip.background =element_rect(fill="white"),
        plot.margin=grid::unit(c(0,0,0,0), "mm"),
        plot.title = element_text(color="black",hjust=0,vjust=1, size=20),
        panel.background = element_rect(fill ="black"),
        panel.grid.major = element_blank())+ 
  scale_fill_gradient2(name="Shipping Hours", low = "black", mid = "dodgerblue",high = "white",na.value = "black", trans = "log", midpoint = log(25000),labels=fancy_scientific) +
  geom_sf(data = world.land,
          fill = "grey30",
          lwd = 0)+ 
  ylim(c(-55,90)) +
  geom_point(data = ASAM, aes(x = lon, y = lat),size = 0.01,color="red") + guides(fill=guide_legend(
    keywidth=0.25,
    keyheight=0.25,
    default.unit="inch")
  ) +
      labs(title="Global shipping and piracy attacks"), width = 8.5, height = 8.5/2)
```

