---
title: "Piracy and Shipping"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(glue)
library(bigrquery)
```

```{r setup, eval=FALSE}
# DON'T RUN IF YOU DON'T NEED TO
# Just look at voyages coming into or out of Nigeria
country_filter <- "(from_country = 'NGA' OR to_country = 'NGA')"

# Define SQL query
sql <-glue(
  "SELECT
*
FROM
[ucsb-gfw:piracy.all_cargo_voyages]
WHERE
{country_filter}"
)
project <-  "ucsb-gfw"

## Run the query    
voyages <- query_exec(sql, project, max_pages = Inf)

write_csv(voyages,"../processed_data/voyages_processed_nga.csv")
```

```{r shipping_data, eval=FALSE}
# DON'T RUN IF YOU DON'T NEED TO

# Define SQL query
sql <-glue(
  "SELECT
*
FROM
[ucsb-gfw:piracy.gridded_shipping_hours]"
)
project <-  "ucsb-gfw"

## Run the query    
gridded_shipping_hours <- query_exec(sql, project, max_pages = Inf)

# Make smaller, to 1 degree cells
gridded_shipping_hours_processed <- gridded_shipping_hours %>%
#  mutate(lat_bin = floor(lat_bin),
#         lon_bin = floor(lon_bin)) %>%
  filter(lat_bin < 90 &
           lat_bin > -90 &
           lon_bin < 180 &
           lon_bin > - 180) %>%
  group_by(year,lat_bin,lon_bin) %>%
  summarize(hours = sum(hours,na.rm=TRUE))

write_csv(gridded_shipping_hours_processed,"../processed_data/gridded_shipping_hours_processed.csv")
```
