---
title: "Piracy and Shipping SQL Queries"
output: html_notebook
---

This notebook contains all the SQL queries done on Google Big Query to generate our data set.

```{r}
# cargo_trips_with_port_labels
sql <-
"
SELECT
  anchorages.mmsi mmsi,
  anchorages.known_geartype vessel_type,
  b.label from_port,
  anchorages.from_anchorage_id from_anchorage_id,
  anchorages.from_anchorage_name from_anchorage_name,
  anchorages.departure_timestamp departure_timestamp,
  c.label to_port,
  anchorages.to_anchorage_id to_anchorage_id,
  anchorages.to_anchorage_name to_anchorage_name,
  anchorages.arrival_timestamp arrival_timestamp
FROM (
  SELECT
    anchor1.mmsi mmsi,
    anchor2.known_geartype known_geartype,
    anchor2.anchorage_id from_anchorage_id,
    anchor2.anchorage_name from_anchorage_name,
    anchor2.event_end departure_timestamp,
    anchor1.anchorage_id to_anchorage_id,
    anchor1.anchorage_name to_anchorage_name,
    anchor1.event_start arrival_timestamp
  FROM (
    SELECT
      vessel_1_id mmsi,
      event_start,
      event_end,
      anchorage_id,
      anchorage_name,
      ROW_NUMBER() OVER (PARTITION BY vessel_1_id ORDER BY event_start) rn
    FROM
      `world-fishing-827.gfw_research.voyage_events_all_vessels_20180307`
    WHERE
      event_type = 'anchorage'
      AND vessel_1_id IN (
      SELECT
        mmsi
      FROM
        `world-fishing-827.gfw_research.vessel_info_20180327`
      WHERE
        known_geartype = 'cargo'
        OR known_geartype = 'tanker') ) anchor1
  JOIN (
    SELECT
      *,
      rn+1 rn_plus
    FROM (
      (SELECT
        vessel_1_id mmsi,
        event_start,
        event_end,
        anchorage_id,
        anchorage_name,
        ROW_NUMBER() OVER (PARTITION BY vessel_1_id ORDER BY event_start) rn
      FROM
        `world-fishing-827.gfw_research.voyage_events_all_vessels_20180307`
      WHERE
        event_type = 'anchorage') voy_info
      LEFT JOIN(
      SELECT
          mmsi mmsi_info,
          known_geartype
      FROM
         `world-fishing-827.gfw_research.vessel_info_20180327`) ves_info
      ON voy_info.mmsi = ves_info.mmsi_info)) anchor2
  ON
    anchor1.mmsi = anchor2.mmsi
    AND anchor1.rn = anchor2.rn_plus) anchorages
LEFT JOIN (
  SELECT
    s2id,
    label
  FROM
    `world-fishing-827.gfw_research.named_anchorages_20171120`) b
ON
  anchorages.from_anchorage_id = b.s2id
LEFT JOIN (
  SELECT
    s2id,
    label
  FROM
    `world-fishing-827.gfw_research.named_anchorages_20171120`) c
ON
  anchorages.to_anchorage_id = c.s2id"
```

```{r}
# all_cargo_AIS_positions_with_ports
sql <- 
"
SELECT
  a.mmsi mmsi,
  vessel_type,
  start_lat,
  start_lon,
  start_timestamp,
  end_lat,
  end_lon,
  end_timestamp,
  hours,
  avg_distance_km,
  from_anchorage,
  from_anchorage_id,
  departure_timestamp,
  to_anchorage,
  to_anchorage_id,
  arrival_timestamp
FROM (
  SELECT
    mmsi,
    lat start_lat,
    lon start_lon,
    timestamp start_timestamp,
    next_lat end_lat,
    next_lon end_lon,
    next_timestamp end_timestamp,
    hours,
    avg_distance_km
  FROM
    `world-fishing-827.gfw_research.pipeline_p_p550_daily`
  WHERE
    mmsi IN (
    SELECT
      mmsi
    FROM
      `world-fishing-827.gfw_research.vessel_info_20180327`
    WHERE
      known_geartype = 'cargo'
      OR known_geartype = 'tanker')) a
JOIN (
  SELECT
    mmsi,
    vessel_type,
    from_anchorage_name from_anchorage,
    from_anchorage_id,
    departure_timestamp,
    to_anchorage_name to_anchorage,
    to_anchorage_id,
    arrival_timestamp
  FROM
    `ucsb-gfw.piracy.cargo_trips_with_port_labels`) anchorages
ON
  a.mmsi = anchorages.mmsi
  AND a.start_timestamp > anchorages.departure_timestamp
  AND a.start_timestamp < anchorages.arrival_timestamp"
```

```{r}
# all_cargo_voyages_gridded
sql <- 
"
SELECT
  ais_info.mmsi mmsi,
  ais_info.vessel_type vessel_type,
  ais_info.lat_bin lat_bin,
  ais_info.lon_bin lon_bin,
  ais_info.from_anchorage from_anchorage,
  ais_info.from_anchorage_id from_anchorage_id,
  ais_info.departure_timestamp departure_timestamp,
  ais_info.to_anchorage to_anchorage,
  ais_info.to_anchorage_id to_anchorage_id,
  ais_info.arrival_timestamp arrival_timestamp,
  ais_info.distance_km distance_km,
  ais_info.hours hours,
  ais_info.ais_pings ais_pings,
  attack_info.hotspot_id hotspot_id,
  attack_info.is_current_hotspot is_current_hotspot,
  attack_info.attacks_last_7_days attacks_last_7_days,
  attack_info.attacks_last_14_days attacks_last_14_days,
  attack_info.attacks_last_21_days attacks_last_21_days,
  attack_info.attacks_last_30_days attacks_last_30_days,
  attack_info.attacks_last_60_days attacks_last_60_days, 
  attack_info.attacks_last_90_days attacks_last_90_days, 
  attack_info.attacks_last_180_days attacks_last_180_days, 
  attack_info.attacks_last_365_days attacks_last_365_days, 
  attack_info.days_since_attack days_since_attack
FROM (
  SELECT
    mmsi,
    vessel_type,
    FLOOR(start_lat/5) * 5 lat_bin,
    FLOOR(start_lon/5) * 5 lon_bin,
    from_anchorage,
    from_anchorage_id,
    departure_timestamp,
    DATE(departure_timestamp) departure_date,
    to_anchorage,
    to_anchorage_id,
    arrival_timestamp,
    SUM(avg_distance_km) distance_km,
    SUM(hours) hours,
    COUNT(*) ais_pings
  FROM
    [piracy.all_cargo_AIS_positions_with_ports]
  GROUP BY
    mmsi,
    vessel_type,
    lat_bin,
    lon_bin,
    from_anchorage,
    from_anchorage_id,
    departure_timestamp,
    departure_date,
    to_anchorage,
    to_anchorage_id,
    arrival_timestamp) ais_info
LEFT JOIN (
  SELECT
    DATE(date) date, 
    hotspot_id, 
    is_current_hotspot,
    lon_bin, 
    lat_bin, 
    attacks_last_7_days, 
    attacks_last_14_days, 
    attacks_last_21_days, 
    attacks_last_30_days, 
    attacks_last_60_days, 
    attacks_last_90_days, 
    attacks_last_180_days, 
    attacks_last_365_days, 
    days_since_attack
  FROM
    [piracy.piracy_attacks] ) attack_info
ON
  ais_info.lat_bin = attack_info.lat_bin
  AND ais_info.lon_bin = attack_info.lon_bin
  AND ais_info.departure_date = attack_info.date"
```

```{r}
# all_cargo_voyages
"
SELECT
  a.mmsi mmsi,
  a.vessel_type vessel_type,
  a.from_anchorage from_anchorage,
  a.from_anchorage_id from_anchorage_id,
  NTH(2, SPLIT(a.from_anchorage, ",")) from_country,
  DATE(a.departure_timestamp) departure_date,
  a.to_anchorage to_anchorage,
  a.to_anchorage_id to_anchorage_id,
  NTH(2, SPLIT(a.to_anchorage, ",")) to_country,
  DATE(a.arrival_timestamp) arrival_date,
  a.total_distance_km total_distance_km,
 6371*ACOS(COS(RADIANS(anchorage_info_to.to_anchorage_lat))*COS(RADIANS(anchorage_info_from.from_anchorage_lat))*COS(RADIANS(anchorage_info_from.from_anchorage_lon)-RADIANS(anchorage_info_to.to_anchorage_lon))+SIN(RADIANS(anchorage_info_to.to_anchorage_lat))*SIN(RADIANS(anchorage_info_from.from_anchorage_lat))) total_haversine_distance_km,
  a.total_hours total_hours,
  a.total_ais_pings total_ais_pings,
  a.hotspot_distance_km hotspot_distance_km,
  a.hotspot_hours hotspot_hours,
  a.hotspot_ais_pings hotspot_ais_pings,
  a.number_hotspots number_hotspots,
  a.attacks_last_7_days attacks_last_7_days,
  a.attacks_last_14_days attacks_last_14_days,
  a.attacks_last_21_days attacks_last_21_days,
  a.attacks_last_30_days attacks_last_30_days,
  a.attacks_last_60_days attacks_last_60_days,
  a.attacks_last_90_days attacks_last_90_days,
  a.attacks_last_180_days attacks_last_180_days,
  a.attacks_last_365_days attacks_last_365_days,
  a.days_since_attack days_since_attack
FROM (
  SELECT
    mmsi,
    vessel_type,
    from_anchorage,
    from_anchorage_id,
    departure_timestamp,
    to_anchorage,
    to_anchorage_id,
    arrival_timestamp,
    SUM(distance_km) total_distance_km,
    SUM(hours) total_hours,
    SUM(ais_pings) total_ais_pings,
    SUM(CASE
        WHEN NOT(is_current_hotspot IS NULL) THEN distance_km
        ELSE NULL END) hotspot_distance_km,
    SUM(CASE
        WHEN NOT(is_current_hotspot IS NULL) THEN hours
        ELSE NULL END) hotspot_hours,
    SUM(CASE
        WHEN NOT(is_current_hotspot IS NULL) THEN ais_pings
        ELSE NULL END) hotspot_ais_pings,
    SUM(is_current_hotspot) number_hotspots,
    SUM(attacks_last_7_days) attacks_last_7_days,
    SUM(attacks_last_14_days) attacks_last_14_days,
    SUM(attacks_last_21_days) attacks_last_21_days,
    SUM(attacks_last_30_days) attacks_last_30_days,
    SUM(attacks_last_60_days) attacks_last_60_days,
    SUM(attacks_last_90_days) attacks_last_90_days,
    SUM(attacks_last_180_days) attacks_last_180_days,
    SUM(attacks_last_365_days) attacks_last_365_days,
    MIN(days_since_attack) days_since_attack
  FROM
    [ucsb-gfw:piracy.all_cargo_voyages_gridded]
  GROUP BY
    mmsi,
    vessel_type,
    from_anchorage,
    from_anchorage_id,
    departure_timestamp,
    to_anchorage,
    to_anchorage_id,
    arrival_timestamp) a
LEFT JOIN (
  SELECT
    s2id,
    lat from_anchorage_lat,
    lon from_anchorage_lon
  FROM
    [world-fishing-827:gfw_research.named_anchorages_20171120] ) anchorage_info_from
ON
  a.from_anchorage_id = anchorage_info_from.s2id
LEFT JOIN (
  SELECT
    s2id,
    lat to_anchorage_lat,
    lon to_anchorage_lon
  FROM
    [world-fishing-827:gfw_research.named_anchorages_20171120] ) anchorage_info_to
ON
  a.to_anchorage_id = anchorage_info_to.s2id"
```



